CartolaFC/CartolaFC/Models/Tecnico.cs
using System.ComponentModel.DataAnnotations;
using CartolaFC.Infra;

namespace CartolaFC.Models
{
    public class Tecnico
    {
        public int TecnicoId { get; set; }

        [Required(ErrorMessage = Mensagens.Tecnico.NomeDeveSerpreenchido)]
        [StringLength(50, MinimumLength = 2, ErrorMessage = Mensagens.Tecnico.NomeDeveTerDe2A50Caracteres)]
        public string Nome { get; set; }

        public string Descricao { get; set; }
    }
}

CartolaFC/CartolaFC/Models/Time.cs
using System.ComponentModel.DataAnnotations;
using CartolaFC.Infra;

namespace CartolaFC.Models
{
    public class Time
    {
        public int TimeId { get; set; }

        [Required(ErrorMessage = Mensagens.Time.NomeDeveSerpreenchido)]
        [StringLength(50, MinimumLength = 2, ErrorMessage = Mensagens.Time.NomeDeveTerDe2A50Caracteres)]
        [Display(Name = "Nome do Time:")]
        public string Nome { get; set; }

        [Required(ErrorMessage = Mensagens.Time.AnoDeFundacaoDeveSerPreenchido)]
        [StringLength(4, MinimumLength = 4, ErrorMessage = Mensagens.Time.AnoDeFundacaoDeveTer4Caracteres)]
        [Display(Name = "Ano de Fundação:")]
        public string AnoDeFundacao { get; set; }

        public string Descricao { get; set; }

        public Tecnico Tecnico { get; set; }
    }
}

CartolaFC/CartolaFC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CartolaFC.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

CartolaFC/CartolaFC/Controllers/TecnicoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CartolaFC.Infra;
using CartolaFC.Models;

namespace CartolaFC.Controllers
{
    public class TecnicoController : Controller
    {
        private readonly DbComum db = new DbComum();

        public ActionResult Index()
        {
            return View(db.Tecnicos.ToList());
        }

        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Tecnico tecnico)
        {
            if (ModelState.IsValid)
            {
                db.Tecnicos.Add(tecnico);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tecnico);
        }

        public ActionResult Editar(int id)
        {
            var tecnico = db.Tecnicos.Find(id);
            return View(tecnico);
        }

        [HttpPost]
        public ActionResult Editar(Tecnico tecnico)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tecnico).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tecnico);
        }

        public ActionResult Excluir(int id)
        {
            var tecnico = db.Tecnicos.Find(id);
            return View(tecnico);
        }

        [HttpPost, ActionName("Excluir")]
        public ActionResult ConfirmaExcluir(int id)
        {
            var tecnico = db.Tecnicos.Find(id);
            db.Tecnicos.Remove(tecnico);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Detalhes(int id)
        {
            var tecnico = db.Tecnicos.Find(id);
            return View(tecnico);
        }
    }
}

CartolaFC/CartolaFC/Controllers/TimeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CartolaFC.Infra;
using CartolaFC.Models;

namespace CartolaFC.Controllers
{
    public class TimeController : Controller
    {
        private DbComum db = new DbComum();

        public ActionResult Index()
        {
            return View(db.Times.Include(x => x.Tecnico).ToList());
        }

        public ActionResult Cadastrar()
        {
            ViewBag.ListaDeTecnicos = new SelectList(db.Tecnicos.ToList(), "TecnicoId", "Nome");
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar([Bind(Exclude = "Tecnico")]Time time, int tecnicoId)
        {
            if (ModelState.IsValid)
            {
                time.Tecnico = db.Tecnicos.Find(tecnicoId);
                db.Times.Add(time);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(time);
        }

        public ActionResult Editar(int id)
        {
            var time = db.Times.Include(x => x.Tecnico).FirstOrDefault(x => x.TimeId == id);

            ViewBag.ListaDeTecnicos = new SelectList(db.Tecnicos.ToList(), "TecnicoId", "Nome", time.Tecnico.TecnicoId);

            return View(time);
        }

        [HttpPost]
        public ActionResult Editar([Bind(Exclude = "Tecnico")]Time time, int tecnicoId)
        {
            if (ModelState.IsValid)
            {
                var timeBanco = db.Times.Find(time.TimeId);
                timeBanco.Descricao = time.Descricao;
                timeBanco.Nome = time.Nome;
                timeBanco.AnoDeFundacao = time.AnoDeFundacao;

                timeBanco.Tecnico = db.Tecnicos.Find(tecnicoId);

                //db.Entry(timeBanco).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(time);
        }

        public ActionResult Excluir(int id)
        {
            var time = db.Times.Include(x => x.Tecnico).FirstOrDefault(x => x.TimeId == id);
            return View(time);
        }

        [HttpPost, ActionName("Excluir")]
        public ActionResult ConfirmaExcluir(int id)
        {
            var time = db.Times.Find(id);
            db.Times.Remove(time);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Detalhes(int id)
        {
            var time = db.Times.Include(x => x.Tecnico).FirstOrDefault(x => x.TimeId == id);
            return View(time);
        }
    }
}

CartolaFC/CartolaFC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Página Inicial</h2>
<p>Bem-vindo ao Cartola FC, use os menus acima para navegar no site.</p>

CartolaFC/CartolaFC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>

    <body>
        <h1>Cartola Futebol Clube</h1>
        <ul>
            <li>
                @Html.ActionLink("Home","Index","Home")
            </li>
            <li>
                @Html.ActionLink("Times","Index","Time")
            </li>
            <li>
                @Html.ActionLink("Técnico","Index","Tecnico")
            </li>
        </ul>
        <section>
            @RenderBody()
        </section>
        <footer>
            CartolaTabajar.com
        </footer>
    </body>
</html>

CartolaFC/CartolaFC/Views/Tecnico/Cadastrar.cshtml
@model CartolaFC.Models.Tecnico
@{
    ViewBag.Title = "Cadastrar Técnico";
}
<h2>
    Cadastrar Técnico</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <fieldset>
        <legend>Técnico</legend>
        <div>
            @Html.LabelFor(model => model.Nome)
        </div>
        <div>
            @Html.EditorFor(model => model.Nome)
            @Html.ValidationMessageFor(model=> model.Nome)
        </div>
        <div>
            @Html.LabelFor(model => model.Descricao)
        </div>
        <div>
            @Html.TextAreaFor(model => model.Descricao)
            @Html.ValidationMessageFor(model=> model.Descricao)
        </div>
        <p>
            <input type="submit" value="Cadastrar" />
        </p>
    </fieldset>
}
<a href="@Url.Action("Index", "Tecnico")" class="voltar">Voltar</a>

CartolaFC/CartolaFC/Views/Tecnico/Detalhes.cshtml
@model CartolaFC.Models.Tecnico
@{
    ViewBag.Title = "Detalhes do Técnico";
}
<h2>
    Detalhes do Técnico</h2>
<fieldset>
    <legend>Técnico</legend>
    <div>
        @Html.LabelFor(model => model.Nome)
    </div>
    <div>
        @Html.DisplayFor(model => model.Nome)
    </div>

    <div>
        @Html.LabelFor(model => model.Descricao)
    </div>
    <div>
        @Html.DisplayFor(model => model.Descricao)
    </div>
</fieldset>
<p>
    <a href="@Url.Action("Editar", "Tecnico", new { id = Model.TecnicoId })" class="voltar">Editar</a>
    <a href="@Url.Action("Index", "Tecnico")" class="voltar">Voltar</a>
</p>

CartolaFC/CartolaFC/Views/Tecnico/Editar.cshtml
@model CartolaFC.Models.Tecnico
@{
    ViewBag.Title = "Editar Técnico";
}
<h2>
    Editar Técnico</h2>
    
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <fieldset>
        <legend>Técnico</legend>
        @Html.HiddenFor(model => model.TecnicoId)
        <div>
            @Html.LabelFor(model => model.Nome)
        </div>
        <div>
            @Html.EditorFor(model => model.Nome)
            @Html.ValidationMessageFor(model => model.Nome)
        </div>

        <div>
            @Html.LabelFor(model => model.Descricao)
        </div>
        <div>
            @Html.TextAreaFor(model => model.Descricao)
            @Html.ValidationMessageFor(model => model.Descricao)
        </div>
        <p>
            <input type="submit" value="Alterar" />
        </p>
    </fieldset>
}
<a href="@Url.Action("Index", "Tecnico")" class="voltar">Voltar</a>

CartolaFC/CartolaFC/Views/Tecnico/Excluir.cshtml
@model CartolaFC.Models.Tecnico
@{
    ViewBag.Title = "Excluir Técnico";
}

<h2>Excluir</h2>
<h3>Deseja mesmo excluir?</h3>
<fieldset>
    <legend>Técnico</legend>
    <div>
        @Html.LabelFor(model=>model.Nome)
    </div>
    <div>
        @Html.DisplayFor(model=>model.Nome)
    </div>
    
    <div>
        @Html.LabelFor(model=>model.Descricao)
    </div>
    <div>
        @Html.DisplayFor(model=>model.Descricao)
    </div>
</fieldset>
@using(Html.BeginForm())
{
    <p>
        <input type="submit" value="Excluir"/>
        <a href="@Url.Action("Index","Tecnico")" class="voltar">Voltar</a>
    </p>
}

CartolaFC/CartolaFC/Views/Tecnico/Index.cshtml
@model IEnumerable<CartolaFC.Models.Tecnico>
@{
    ViewBag.Title = "Listagem de Técnico";
}
<h2>
    Listagem de Técnico</h2>
<p>
    <a href="@Url.Action("Cadastrar", "Tecnico")" class="voltar">Cadatrar novo Técnico</a>
</p>
<table>
    <tr>
        <th>
            Nome
        </th>
        <th>
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Nome
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.TecnicoId })
                @Html.ActionLink("Excluir", "Excluir", new { id = item.TecnicoId })
                @Html.ActionLink("Detalhes", "Detalhes", new { id = item.TecnicoId })
            </td>
        </tr>
    }
</table>

CartolaFC/CartolaFC/Views/Time/Cadastrar.cshtml
@model CartolaFC.Models.Time
@{
    ViewBag.Title = "Cadastrar Time";
}
<h2>
    Cadastrar Time</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <fieldset>
        <legend>Time</legend>
        <div>
            @Html.LabelFor(model => model.Nome)
        </div>
        <div>
            @Html.EditorFor(model => model.Nome)
            @Html.ValidationMessageFor(model => model.Nome)
        </div>
        <div>
            @Html.LabelFor(model => model.AnoDeFundacao)
        </div>
        <div>
            @Html.EditorFor(model => model.AnoDeFundacao)
            @Html.ValidationMessageFor(model => model.AnoDeFundacao)
        </div>
        <div>
            @Html.LabelFor(model => model.Descricao)
        </div>
        <div>
            @Html.TextAreaFor(model => model.Descricao)
            @Html.ValidationMessageFor(model => model.Descricao)
        </div>
        <div>
            @Html.LabelFor(model => model.Tecnico.Nome)
        </div>
        <div>
            @Html.DropDownList("tecnicoId", (SelectList)ViewBag.ListaDeTecnicos)
        </div>
        <p>
            <input type="submit" value="Cadastrar" />
        </p>
    </fieldset>
}
<a href="@Url.Action("Index", "Time")" class="voltar">Voltar</a>

CartolaFC/CartolaFC/Views/Time/Detalhes.cshtml
@model CartolaFC.Models.Time
@{
    ViewBag.Title = "Detalhes do Time";
}
<h2>
    Detalhes do Time</h2>
<fieldset>
    <legend>Time</legend>
    <div>
        @Html.LabelFor(model => model.Nome)
    </div>
    <div>
        @Html.DisplayFor(model => model.Nome)
    </div>
    <div>
        @Html.LabelFor(model => model.AnoDeFundacao)
    </div>
    <div>
        @Html.DisplayFor(model => model.AnoDeFundacao)
    </div>
    <div>
        @Html.LabelFor(model => model.Descricao)
    </div>
    <div>
        @Html.DisplayFor(model => model.Descricao)
    </div>
    <div>
        @Html.LabelFor(model => model.Tecnico.Nome)
    </div>
    <div>
        @Html.DisplayFor(model => model.Tecnico.Nome)
    </div>
    <div>
        @Html.LabelFor(model => model.Tecnico.Descricao)
    </div>
    <div>
        @Html.DisplayFor(model => model.Tecnico.Descricao)
    </div>
</fieldset>
<p>
    <a href="@Url.Action("Editar", "Time", new { id = Model.TimeId })" class="voltar">Editar</a>
    <a href="@Url.Action("Index", "Time")" class="voltar">Voltar</a>
</p>

CartolaFC/CartolaFC/Views/Time/Editar.cshtml
@model CartolaFC.Models.Time
@{
    ViewBag.Title = "Editar Time";
}
<h2>
    Editar Time</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <fieldset>
        <legend>Time</legend>
        @Html.HiddenFor(model => model.TimeId)
        <div>
            @Html.LabelFor(model => model.Nome)
        </div>
        <div>
            @Html.EditorFor(model => model.Nome)
            @Html.ValidationMessageFor(model => model.Nome)
        </div>
        <div>
            @Html.LabelFor(model => model.AnoDeFundacao)
        </div>
        <div>
            @Html.EditorFor(model => model.AnoDeFundacao)
            @Html.ValidationMessageFor(model => model.AnoDeFundacao)
        </div>
        <div>
            @Html.LabelFor(model => model.Descricao)
        </div>
        <div>
            @Html.TextAreaFor(model => model.Descricao)
            @Html.ValidationMessageFor(model => model.Descricao)
        </div>
        <div>
            @Html.LabelFor(model => model.Tecnico.Nome)
        </div>
        <div>
            @Html.DropDownList("tecnicoId", (SelectList)ViewBag.ListaDeTecnicos)
        </div>
        <p>
            <input type="submit" value="Alterar" />
        </p>
    </fieldset>
}
<a href="@Url.Action("Index", "Time")" class="voltar">Voltar</a>

CartolaFC/CartolaFC/Views/Time/Excluir.cshtml
@model CartolaFC.Models.Time
@{
    ViewBag.Title = "Exclui Times";
}
<h2>
    Excluir</h2>
<h3>
    Deseja mesmo excluir?</h3>
<fieldset>
    <legend>Time</legend>
    <div>
        @Html.LabelFor(model => model.Nome)
    </div>
    <div>
        @Html.DisplayFor(model => model.Nome)
    </div>
    <div>
        @Html.LabelFor(model => model.AnoDeFundacao)
    </div>
    <div>
        @Html.DisplayFor(model => model.AnoDeFundacao)
    </div>
    <div>
        @Html.LabelFor(model => model.Tecnico.Nome)
    </div>
    <div>
        @Html.DisplayFor(model => model.Tecnico.Nome)
    </div>
</fieldset>
@using (Html.BeginForm())
{
    <p>
        <input type="submit" value="Excluir" />
        <a href="@Url.Action("Index", "Time")" class="voltar">Voltar</a>
    </p>
}

CartolaFC/CartolaFC/Views/Time/Index.cshtml
@model IEnumerable<CartolaFC.Models.Time>
@{
    ViewBag.Title = "Listagem de Times";
}
<h2>
    Listagem de Times</h2>
<p>
    <a href="@Url.Action("Cadastrar", "Time")" class="voltar">Cadatrar novo time </a>
</p>
<table>
    <tr>
        <th>
            Nome
        </th>
        <th>
            Técnico
        </th>
        <th>
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Nome
            </td>
            <td>
                @item.Tecnico.Nome
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.TimeId })
                @Html.ActionLink("Excluir", "Excluir", new { id = item.TimeId })
                @Html.ActionLink("Detalhes", "Detalhes", new { id = item.TimeId })
            </td>
        </tr>
    }
</table>